import './style.css';
import { initPreloader } from './modules/preloader.js';
import { initLenis } from './core/lenis.js';
import { initHeroVideoParallax } from './modules/hero-video-parallax.js';
import { initHeroTextSplit } from './modules/hero-text-split.js';
import { initTitleLineReveal } from './modules/title-line-reveal.js';
import { initNavLogoTheme } from './modules/nav-logo-theme.js';
import { initThemeColorSwap } from './modules/theme-color-swap.js';
import { initButtonDemo } from './modules/button-demo.js';
import { initSecondaryButtonRoll } from './modules/second-button.js';
import { initSafariVideoSwap } from './modules/safari-video-swap.js';
import { initArrowButton } from './modules/arrow-button.js';
import { initFootIcon } from './modules/foot-icon.js';
import { initMorphSvgAim } from './modules/morph-svg-aim.js';
import { initTimeline } from './modules/timeline.js';
import { initMenu } from './modules/menu.js';
import { initRequestModal } from './modules/request-modal.js';
import { initTabs } from './modules/tabs.js';
import { initSolutionCarousel } from './modules/solution-carousel.js';
import { initCtaParallax } from './modules/cta-parallax.js';
import { initEveryChamberReveal } from './modules/every-chamber-reveal.js';
import { initNavProgress } from './modules/nav-progress.js';
import { initCtaReveal } from './modules/cta-reveal.js';
import { initOverviewReveal } from './modules/overview-reveal.js';
import { initBodyThemeScroll } from './modules/body-theme-scroll.js';

initPreloader();
initLenis();
initHeroVideoParallax();
initHeroTextSplit();
initTitleLineReveal();
initNavLogoTheme();
initThemeColorSwap();
initButtonDemo();
initSecondaryButtonRoll();
initSafariVideoSwap();
initArrowButton();
initFootIcon();
initMorphSvgAim();
initTimeline();
initMenu();
initRequestModal();
initTabs();
initSolutionCarousel();
initCtaParallax();
initEveryChamberReveal();
initNavProgress();
initCtaReveal();
initOverviewReveal();
//initBodyThemeScroll();
